### ISSUE TITLE
fix docker stop issue

### ISSUE THREAD

**Issue by diroussel** [aesteve/gradle-docker-download-libs#1]
You seem to be using the 'shell' version of ENTRYPOINT in your Dockerfile.  According the the [docs](https://docs.docker.com/engine/reference/builder/#shell-form-entrypoint-example) you need to use the 'exec' shell command, otherwise signals won't be handled correctly, and "docker stop" doesn't work.

The other way to fix is like this (copied from my own working code):
```
FROM adoptopenjdk:11-jre-hotspot

COPY target/lib /run/lib
ADD target/main.jar /run/main.jar

ENTRYPOINT ["java", "-jar", "run/main.jar"]
```

And then use the manifest to reference the dependency jars, and then you don't need blobbing, and thus don't need the shell in the ENTRYPOINT.

**Comment by aesteve** [comment]
Thanks a lot!

**Comment by aesteve** [comment]
How are you generating the manifest (to point at `/run/lib`), though? Could you please tell me a little bit more about that so that I can update the example? 

That'd be really awesome of you, thank you!

**Comment by diroussel** [comment]
The project I have tested with uses maven, and this I how I configured the maven-jar-plugin:
```xml
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <version>3.1.2</version>
        <configuration>
          <finalName>main</finalName>
          <archive>
            <manifest>
              <addClasspath>true</addClasspath>
              <mainClass>myapp.service.app.Application</mainClass>
              <classpathPrefix>lib/</classpathPrefix>
            </manifest>
          </archive>
        </configuration>
      </plugin>
```
Here the main class is set, which is quite normal.  But also the `addClasspath` and `classpathPrefix` settings add the dependencies to the manifest.

So this is my Dockerfile
```
FROM adoptopenjdk:11-jre-hotspot

COPY target/lib /run/lib
ADD target/main.jar /run/main.jar

ENTRYPOINT ["java", "-jar", "run/main.jar"]
```

And this is what the manifest looks like inside my main.jar
```
Manifest-Version: 1.0
Created-By: Maven Archiver 3.4.0
Build-Jdk-Spec: 11
Class-Path: lib/vertx-core-3.8.2.jar lib/blah-blah-blah.jar lib/swagger-ui-3.24.
 0.jar
Main-Class: myapp.service.app.Application
```

Note that the `Class-Path:` entry in the manifest treat the entries as relative to the current jar file.  So this means that `lib/` and `main.jar` should be in the same folder.  See [the manifest docs](https://docs.oracle.com/javase/tutorial/deployment/jar/manifestindex.html) for more info.

There are some suggestions on how to do this in gradle here: https://stackoverflow.com/questions/22659463/add-classpath-in-manifest-using-gradle?rq=1

**Comment by aesteve** [comment]
Thank you, should be easy to adapt to Gradle!

**Comment by aesteve** [comment]
Easy fix indeed. Thanks a lot for the report, and for your help fixing it.
